### ISSUE TITLE
Still unable to find image ibmnode:v1.1

### ISSUE THREAD

**Issue by iainhouston** [osipov/district-insurance-sample#3] opened 2016-07-18 17:39 UTC
I have a separate issue with Bluemix in that I can't `cf ic init` using my space in the US South Region - someone is looking into this for me. But in the meantime I am unable to pull the `ibmnode` image from the registry when logged in  to the UK Region as I see the registry is hard-coded with the US endpoint.

Is there any chance you could have the `make` pick up the `ibmnode` from the region in which the `make` is running?

**Comment by osipov** [comment] 2016-07-18 18:31
Hi @iainhouston -- the region isn't hardcoded in the make file. You just need to specify your Cloud Foundry API endpoint when running make, for example the following will log in your client to UK. Note that I overrode the default when prompted for the api.ng.bluemix.net to point to the UK endpoint instead.

```
make build-release-local
Image [district-insurance-sample]: 
make[1]: Entering directory '/home/docker/district-insurance-sample'
Cloud Foundry API endpoint [https://api.ng.bluemix.net]: https://api.eu-gb.bluemix.net
cf login -a https://api.eu-gb.bluemix.net
```

**Comment by iainhouston** [comment] 2016-07-18 20:30
Hmmm.Yes, I too overode the US endpoint with the UK one. See ...  I'm logged in to the `eu-gb` region but it's trying to source the image `FROM registry.ng.bluemix.net/ibmnode:v1.1`. Shouldn't it be trying `FROM registry.eu-gb.bluemix.net/ibmnode:v1.1`? (Fuller transcript available should you require it.)

```
...

Running Environment Variable Groups:
BLUEMIX_REGION: ibm:yp:eu-gb

Staging Environment Variable Groups:
BLUEMIX_REGION: ibm:yp:eu-gb

Note the Tradeoff Analytics password and username above and copy/paste them when prompted
Press any key to continue.
make[1]: Leaving directory '/home/docker/district-insurance-sample'
make[1]: Entering directory '/home/docker/district-insurance-sample'
cp scripts/build/Dockerfile .
cp scripts/build/.dockerignore .
docker build -t district-insurance-sample .
Sending build context to Docker daemon 6.992 MB
Step 1 : FROM registry.ng.bluemix.net/ibmnode:v1.1
Pulling repository registry.ng.bluemix.net/ibmnode
Error: image ibmnode:v1.1 not found
    ...
```

**Comment by osipov** [comment] 2016-07-18 21:07
@iainhouston thanks for the report -- i couldn't reproduce your problem because with my account, when I logged into the UK region, I also obtained read access to the US region to retrieve the ibmnode:v1.1 Docker image. 

This will take a while to figure out because you ran into an interesting issue since Dockerfiles require FQDN in the FROM statement of the Dockerfile (issue below) so I can't change the registry using the environment variable settings https://github.com/docker/docker/issues/7203

I'll look into what's the best way to address this, but in the meantime if you'd like a quick fix, you can fork and change the following Dockerfile to point to your UK registry. 
https://github.com/osipov/district-insurance-sample/blob/master/scripts/build/Dockerfile#L3

**Comment by iainhouston** [comment] 2016-07-18 22:30
@osipov thanks for looking into this and I will follow your advice at the next opportunity. I can't help thinking that I don't have access to the US registry because of this other issue I mentioned: namely a key seems to have been corrupted in my US South region credentials. Bluemix support are on the case. Although I can't see why the make is looking for a US ibmnode image when there is one in the UK registry in any case.

**Comment by osipov** [comment] 2016-07-18 22:36
@iainhouston the problem isn't with the make script. Note that make uses the static Dockerfile I referenced earlier and as part of the Docker image definition the Dockerfile pulls from the US registry.  The best practice with Dockerfiles is to keep them static because a Dockerfile is a fixed record of provenance for an image.  So you would either have to get your US credentials to work or change the Dockerfile to pull from the UK region. Neither solution is a good one long term but I'm looking into it.

**Comment by iainhouston** [comment] 2016-07-19 02:51
What you say makes perfect sense @osipov . This is not your issue but FYI The Bluemix support guys are looking into my authentication issue. Of course they said "Can you please install cflci at GitHub rather than pivotal?" T  

he pivotal one is for the Linux Docker Server we've `ssh`'d into right? Anyway  I tried `cf ic init` on my OS X bash and still failed. So it's not the Pivotal sourced cli. I sent them a cf trace so hopefully they can see what's up.

Attached failing session (without cf trace) in case you're inclined to have a look.
[sample fails.txt](https://github.com/osipov/district-insurance-sample/files/370571/sample.fails.txt)

**Comment by osipov** [comment] 2016-07-19 12:55
i suggest trying to create a test container in the US region using the web UI. if you can provision the containers that way, the API should work too. if it doesn't work, then you may get some additional error messages indicating why you are having the issue. i'm going to close this issue --  since we established that the problem isn't with this code.

**Closed as completed** 2016-07-19 12:55 UTC
